#!/usr/bin/env python3
"""Install teamflow, and set projects up to use the installed tool.

install-tool <checkout> <data-dir> <bin-dir> <dev: 0|1>
    Copy the shipped files of a teamflow checkout to <data-dir>/<version>,
    named by `git describe`, point <data-dir>/current at it, and link
    <bin-dir>/teamflow to the launcher. A development install points
    current at the checkout itself.
stubs <tool-home> <history-source> <root>
    Write the stub skills of every shipped skill into .claude/skills and
    .agents/skills. A stub loads its instructions from the installed tool.
unvendor <tool-home> <history-source> <root>
    Remove the teamflow files that older versions copied into the project,
    while they are unmodified. Edited role files stay as project overrides.
set-version <config> <version>
    Record the lowest teamflow version the project needs.
migrate <root> <git-common-dir>
    Move state left by teamflow versions that used the name ai-team:
    .git/ai-team, .ai-team-worktrees/, and ai-team/<id> branches.
drop-pane-delegator <config>
    Remove the [pane.delegator] section of the removed full-team mode.
note-new <tool-home> <root> <type> <title>
    Create a project note from the type's template at
    docs/notes/<type>s/<YYYY-MM-DD-HHMM>-<slug>.md and print its path.
"""

from datetime import datetime
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unicodedata

SKILLS = ("teamflow", "teamflow-resume", "teamflow-kill", "teamflow-workers", "teamflow-trim")
SCRIPTS = ("scripts/teamflow", "scripts/teamflow_workers.py", "scripts/teamflow_scaffold.py",
           "scripts/teamflow_setup.py")
SHIPPED_DIRS = ((".agents/lib", "*.sh"), (".agents/roles", "*.md"), (".agents/doc-templates", "*.md"))
SHIPPED_FILES = SCRIPTS + (".agents/AGENTS-SECTION.md", ".agents/teamflow.conf", "CHANGES.md", "README.md",
                         "LICENSE")
MANIFEST = ".agents/teamflow-manifest"
STUB_MARK = "<!-- teamflow stub: generated by teamflow init, which overwrites edits -->"
REPOSITORY = "https://github.com/jaechoidev/teamflow"
LEGACY = "ai-team"
MAILBOX = "teamflow"
WORKTREES = ".teamflow-worktrees"
LEGACY_WORKTREES = ".ai-team-worktrees"


class ScaffoldError(Exception):
    pass


def git(*args, check=True):
    result = subprocess.run(["git", *args], capture_output=True, text=True)
    if check and result.returncode:
        raise ScaffoldError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result


def blob_id(path, algorithm="sha1"):
    data = Path(path).read_bytes()
    digest = hashlib.new(algorithm)
    digest.update(b"blob %d\0" % len(data))
    digest.update(data)
    return digest.hexdigest()


def shipped_history(source):
    """Blob ids of every committed version of each path in a teamflow checkout."""
    if not source or not Path(source).is_dir():
        return "sha1", {}
    source = Path(source)
    top = git("-C", str(source), "rev-parse", "--show-toplevel", check=False)
    if top.returncode or Path(top.stdout.strip()).resolve() != source.resolve():
        return "sha1", {}
    fmt = git("-C", str(source), "rev-parse", "--show-object-format", check=False).stdout.strip() or "sha1"
    log = git("-C", str(source), "log", "--all", "--format=", "--raw", "--no-abbrev", "--no-renames", check=False)
    history = {}
    for line in log.stdout.splitlines():
        if not line.startswith(":") or "\t" not in line:
            continue
        meta, path = line.split("\t", 1)
        history.setdefault(path, set()).update(meta.split()[2:4])
    return fmt, history


def read_manifest(root):
    path = root / MANIFEST
    entries = {}
    if path.is_file():
        for line in path.read_text().splitlines():
            if line and not line.startswith("#") and " " in line:
                blob, rel = line.split(" ", 1)
                entries[rel] = blob
    return entries


def write_atomic(path, data, mode=0o644):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
        os.chmod(temp, mode)
        os.replace(temp, path)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


def is_pristine(path, source_rel, rel, manifest, fmt, history):
    """An older teamflow wrote this file and nobody edited it since."""
    if manifest.get(rel) == blob_id(path):
        return True
    return blob_id(path, fmt) in history.get(source_rel, ())


def shipped_paths(checkout):
    """Paths, relative to a checkout, that make up an installed teamflow."""
    paths = [rel for rel in SHIPPED_FILES if (checkout / rel).is_file()]
    for folder, pattern in SHIPPED_DIRS:
        paths += [f"{folder}/{f.name}" for f in sorted((checkout / folder).glob(pattern))]
    for skill in SKILLS:
        if not (checkout / "skills" / skill / "SKILL.md").is_file():
            raise ScaffoldError(f"{checkout} is not a complete teamflow checkout (missing skills/{skill}/SKILL.md)")
        for source in sorted((checkout / "skills" / skill).rglob("*")):
            if source.is_file() and not source.name.endswith(".new") and source.name != ".DS_Store":
                paths.append(source.relative_to(checkout).as_posix())
    for rel in SCRIPTS:
        if not (checkout / rel).is_file():
            raise ScaffoldError(f"{checkout} is not a complete teamflow checkout (missing {rel})")
    return paths


def relink(link, target):
    """Point a symlink at target, replacing an older link atomically."""
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.exists() and not link.is_symlink():
        raise ScaffoldError(f"{link} exists and is not a link. Move it aside, then install again")
    temp = link.with_name(f".{link.name}.{os.getpid()}")
    if temp.is_symlink() or temp.exists():
        temp.unlink()
    temp.symlink_to(target)
    os.replace(temp, link)


def install_tool(checkout, data, bin_dir, dev):
    described = git("-C", str(checkout), "describe", "--tags", "--always", "--dirty", check=False)
    if described.returncode:
        raise ScaffoldError(f"{checkout} is not a git checkout. Install from a clone of {REPOSITORY}")
    version = described.stdout.strip()
    paths = shipped_paths(checkout)
    data.mkdir(parents=True, exist_ok=True)
    if dev:
        target = checkout
    else:
        target = data / version
        staging = Path(tempfile.mkdtemp(prefix=".install-", dir=data))
        for rel in paths:
            destination = staging / rel
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(checkout / rel, destination)
        (staging / "version").write_text(version + "\n")
        if target.exists():
            old = data / f".replaced-{version}-{os.getpid()}"
            target.rename(old)
            staging.rename(target)
            shutil.rmtree(old, ignore_errors=True)
        else:
            staging.rename(target)
    relink(data / "current", target)
    (data / "source").write_text(f"{checkout}\n")
    relink(bin_dir / "teamflow", data / "current" / "scripts" / "teamflow")
    say(f"installed teamflow {version}" + (" (development: runs the checkout directly)" if dev else f" in {target}"))
    say(f"command: {bin_dir / 'teamflow'}")
    if str(bin_dir) not in os.environ.get("PATH", "").split(os.pathsep):
        say(f"{bin_dir} is not on PATH. Add it in your shell profile, for example: export PATH=\"{bin_dir}:$PATH\"")


def frontmatter(skill_file):
    text = skill_file.read_text()
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not match:
        raise ScaffoldError(f"{skill_file} has no frontmatter")
    fields = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def stub_text(name, description):
    return f"""---
name: {name}
description: {description}
---

{STUB_MARK}

Run `teamflow guide {name}` and follow the instructions it prints.

If the `teamflow` command is not found, this project uses teamflow (see
`teamflow =` in `teamflow.conf` for the version it needs), but teamflow is
not installed on this machine. Recommend that the user install it:

    git clone {REPOSITORY} ~/code/teamflow
    ~/code/teamflow/install

Do not install it without the user's approval.
"""


def stubs(home, source, root):
    fmt, history = shipped_history(source)
    manifest = read_manifest(root)
    written, kept = [], []
    for skill in SKILLS:
        fields = frontmatter(home / "skills" / skill / "SKILL.md")
        text = stub_text(fields.get("name", skill), fields.get("description", ""))
        for scope in (".claude/skills", ".agents/skills"):
            rel = f"{scope}/{skill}/SKILL.md"
            path = root / rel
            if path.is_file():
                current = path.read_text()
                if current == text:
                    continue
                if STUB_MARK not in current and not is_pristine(path, f"skills/{skill}/SKILL.md", rel,
                                                                 manifest, fmt, history):
                    write_atomic(path.with_name("SKILL.md.new"), text.encode())
                    kept.append(rel)
                    continue
            write_atomic(path, text.encode())
            staged = path.with_name("SKILL.md.new")
            if staged.exists():
                staged.unlink()
            written.append(rel)
    if written:
        say(f"wrote {len(written)} stub skills that load their instructions from the installed teamflow")
    for rel in kept:
        say(f"{rel} has local edits, so it was kept. The stub is at {rel}.new")
    for skill in SKILLS:
        for scope in (".claude/skills", ".agents/skills"):
            print(f"{scope}/{skill}/SKILL.md")


def unvendor(home, source, root):
    """Remove files older versions copied into the project, while unmodified."""
    fmt, history = shipped_history(source)
    manifest = read_manifest(root)
    candidates = [rel for rel in SCRIPTS + (".agents/AGENTS-SECTION.md",)]
    for folder, pattern in SHIPPED_DIRS:
        candidates += [f"{folder}/{f.name}" for f in sorted((root / folder).glob(pattern))]
    removed, overrides, leftovers = [], [], []
    for rel in candidates:
        path = root / rel
        if not path.is_file():
            continue
        staged = path.with_name(path.name + ".new")
        if is_pristine(path, rel, rel, manifest, fmt, history):
            path.unlink()
            removed.append(rel)
            if staged.exists():
                staged.unlink()
        elif rel.startswith(".agents/roles/"):
            overrides.append(rel)
        else:
            leftovers.append(rel)
    if (root / MANIFEST).exists():
        (root / MANIFEST).unlink()
        removed.append(MANIFEST)
    for folder in ("scripts", ".agents/lib", ".agents/doc-templates", ".agents/roles"):
        try:
            (root / folder).rmdir()
        except OSError:
            pass
    if removed:
        say(f"removed {len(removed)} teamflow files older versions copied here. The installed teamflow provides them now")
    for rel in overrides:
        say(f"kept {rel}: it has local edits, so it overrides the installed default role")
    for rel in leftovers:
        say(f"{rel} has local edits. teamflow no longer uses it: review it, then delete it")


def set_version(config, version):
    match = re.match(r"v?(\d+)\.(\d+)\.(\d+)", version)
    path = Path(config)
    if not match or not path.is_file():
        return
    wanted = tuple(int(n) for n in match.groups())
    text = path.read_text()
    current = re.search(r"(?m)^teamflow\s*=\s*v?(\d+)\.(\d+)\.(\d+)\s*$", text)
    if current and tuple(int(n) for n in current.groups()) >= wanted:
        return
    line = f"teamflow = {'.'.join(map(str, wanted))}\n"
    if current:
        text = text[:current.start()] + line.rstrip("\n") + text[current.end():]
    elif re.search(r"(?m)^\[workspace\]\s*$", text):
        text = re.sub(r"(?m)^(\[workspace\]\s*\n)", lambda m: m.group(1) + line, text, count=1)
    else:
        text = "[workspace]\n" + line + "\n" + text
    path.write_text(text)


def live_session(record):
    """Session name when the launch record still matches a running tmux session."""
    if not record.is_file():
        return ""
    values = dict(line.split("=", 1) for line in record.read_text().splitlines() if "=" in line)
    name, created = values.get("SESSION", ""), values.get("CREATED", "")
    if not name:
        return ""
    try:
        listing = subprocess.run(["tmux", "list-sessions", "-F", "#{session_created} #{session_name}"],
                                 capture_output=True, text=True).stdout
    except FileNotFoundError:
        return ""
    for line in listing.splitlines():
        stamp, _, running = line.partition(" ")
        if running == name and stamp == created:
            return name
    return ""


def legacy_worktrees(root):
    """Registered worktrees under .ai-team-worktrees/, as (path, prunable) pairs."""
    listing = git("-C", str(root), "worktree", "list", "--porcelain").stdout
    base = (root / LEGACY_WORKTREES).resolve()
    found = []
    for block in listing.strip().split("\n\n"):
        fields = [line.split(" ", 1) for line in block.splitlines()]
        info = {pair[0]: (pair[1] if len(pair) > 1 else "") for pair in fields}
        path = Path(info.get("worktree", ""))
        if path.parent.resolve() == base:
            found.append((path, "prunable" in info))
    return found


def migrate(root, common):
    legacy, mailbox = common / LEGACY, common / MAILBOX
    old_trees, new_trees = root / LEGACY_WORKTREES, root / WORKTREES
    branches = git("-C", str(root), "for-each-ref", "--format=%(refname:strip=2)",
                   f"refs/heads/{LEGACY}/").stdout.split()
    trees = legacy_worktrees(root)
    if not (legacy.exists() or old_trees.exists() or branches or trees):
        return
    session = live_session(legacy / "active")
    if session:
        raise ScaffoldError(
            f"session {session} runs from the old .git/{LEGACY} state. Nothing was changed. "
            "Stop it with scripts/teamflow --kill, then run this command again to move that "
            f"state to .git/{MAILBOX}.")
    conflicts = [str(new_trees / path.name) for path, prunable in trees
                 if not prunable and (new_trees / path.name).exists()]
    if legacy.is_dir() and mailbox.is_dir():
        conflicts += [str(mailbox / child.name) for child in legacy.iterdir()
                      if child.name != "workers.lock" and (mailbox / child.name).exists()]
    if conflicts:
        raise ScaffoldError("cannot move old teamflow state, because these paths already exist: "
                            + ", ".join(conflicts))
    if legacy.is_dir():
        mailbox.mkdir(exist_ok=True)
        for child in legacy.iterdir():
            target = mailbox / child.name
            if target.exists():
                child.unlink()  # an empty workers.lock, recreated on demand
            else:
                child.rename(target)
        legacy.rmdir()
        say(f"moved the mailbox from .git/{LEGACY} to .git/{MAILBOX}")
    for path, prunable in trees:
        if prunable:
            continue
        new_trees.mkdir(exist_ok=True)
        git("-C", str(root), "worktree", "move", str(path), str(new_trees / path.name))
        say(f"moved worktree {LEGACY_WORKTREES}/{path.name} to {WORKTREES}/{path.name}")
    for branch in branches:
        target = MAILBOX + branch[len(LEGACY):]
        if git("-C", str(root), "show-ref", "--verify", "--quiet", f"refs/heads/{target}", check=False).returncode == 0:
            say(f"kept branch {branch}, because {target} already exists")
            continue
        git("-C", str(root), "branch", "-m", branch, target)
        say(f"renamed branch {branch} to {target}")
    if old_trees.is_dir():
        (old_trees / ".DS_Store").unlink(missing_ok=True)
        try:
            old_trees.rmdir()
        except OSError:
            say(f"{LEGACY_WORKTREES}/ still holds files that are not worktrees. Review and remove it by hand")
    exclude = common / "info" / "exclude"
    if exclude.is_file() and not old_trees.exists():
        lines = exclude.read_text().splitlines(keepends=True)
        kept = [line for line in lines if line.strip() != f"{LEGACY_WORKTREES}/"]
        if kept != lines:
            exclude.write_text("".join(kept))


def drop_pane_delegator(config):
    """Remove the [pane.delegator] section of the removed full-team mode."""
    path = Path(config)
    if not path.is_file():
        return
    lines = path.read_text().splitlines(keepends=True)
    start = next((i for i, line in enumerate(lines) if line.strip() == "[pane.delegator]"), None)
    if start is None:
        return
    end = next((i for i in range(start + 1, len(lines)) if lines[i].lstrip().startswith("[")), len(lines))
    path.write_text("".join(lines[:start] + lines[end:]))
    say(f"removed [pane.delegator] from {path.name}: the Delegator always runs in your own agent session")


def note_new(home, root, kind, title):
    """Create a note named by its creation time, so a folder sorts in the
    order notes were written. The name never changes later, because links
    to the note use it."""
    templates = home / ".agents" / "doc-templates"
    kinds = sorted(f.stem for f in templates.glob("*.md") if f.name != "README.md")
    if kind not in kinds:
        raise ScaffoldError(f"no note type {kind!r}. Types: {', '.join(kinds)}")
    slug = re.sub(r"[\W_]+", "-", unicodedata.normalize("NFKC", title).lower()).strip("-")[:60].rstrip("-")
    if not slug:
        raise ScaffoldError("the title needs a letter or digit to name the file")
    folder = root / "docs" / "notes" / f"{kind}s"
    for existing in sorted(folder.glob(f"*-{slug}.md")):
        if re.fullmatch(rf"\d{{4}}-\d{{2}}-\d{{2}}-\d{{4}}-{re.escape(slug)}\.md", existing.name):
            raise ScaffoldError(f"{existing.relative_to(root)} has this title. Update it, or choose another title")
    now = datetime.now()
    path = folder / f"{now:%Y-%m-%d-%H%M}-{slug}.md"
    text = (templates / f"{kind}.md").read_text()
    folder.mkdir(parents=True, exist_ok=True)
    with open(path, "x") as f:  # never overwrite a note
        f.write(text.replace("{{title}}", title).replace("{{date}}", f"{now:%Y-%m-%d}"))
    print(path.relative_to(root))


def say(message):
    print(f"teamflow: {message}", file=sys.stderr)


def main(argv):
    command, args = (argv[0], argv[1:]) if argv else ("", [])
    if command == "install-tool" and len(args) == 4:
        install_tool(Path(args[0]).resolve(), Path(args[1]), Path(args[2]), args[3] == "1")
    elif command == "stubs" and len(args) == 3:
        stubs(Path(args[0]).resolve(), args[1], Path(args[2]).resolve())
    elif command == "unvendor" and len(args) == 3:
        unvendor(Path(args[0]).resolve(), args[1], Path(args[2]).resolve())
    elif command == "set-version" and len(args) == 2:
        set_version(args[0], args[1])
    elif command == "migrate" and len(args) == 2:
        migrate(Path(args[0]), Path(args[1]))
    elif command == "drop-pane-delegator" and len(args) == 1:
        drop_pane_delegator(args[0])
    elif command == "note-new" and len(args) == 4:
        note_new(Path(args[0]).resolve(), Path(args[1]).resolve(), args[2], args[3])
    else:
        raise ScaffoldError("usage: see the header of teamflow_scaffold.py")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except (ScaffoldError, OSError) as exc:
        print(f"teamflow: {exc}", file=sys.stderr)
        sys.exit(1)
